# Generated by Django 4.2.1 on 2023-06-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_delete_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='charecter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='photo')),
                ('desc', models.TextField()),
            ],
        ),
    ]
